default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: eslint
        args: ["--fix"]
        name: eslint
        entry: bash -c "cd recruiter-app-test && npx eslint --fix 'src/'"
        language: system
        files: \.tsx?$
  - repo: local
    hooks:
      # in case of probleme with flow in pre-commits on ubuntu, see
      # https://github.com/facebook/flow/issues/1491#issuecomment-317507334
      # sudo sysctl fs.inotify.max_user_watches=65536
      - id: typescript
        name: typescript
        entry: tsc -p ./recruiter-app-test/tsconfig.json
        language: system
        files: \.tsx?$
        pass_filenames: false
